/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    'advisory-subcategory': AdvisorySubcategory;
    advisory: Advisory;
    'class-news': ClassNew;
    'classification-ships': ClassificationShip;
    classifications: Classification;
    compliance: Compliance;
    locations: Location;
    news: News;
    pdf: Pdf;
    'portal-resources': PortalResource;
    regulations: Regulation;
    'regulatory-updates': RegulatoryUpdate;
    'research-programs': ResearchProgram;
    'research-report-categories': ResearchReportCategory;
    'research-reports': ResearchReport;
    software: Software;
    'training-course-categories': TrainingCourseCategory;
    media: Media;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    'advisory-subcategory': AdvisorySubcategorySelect<false> | AdvisorySubcategorySelect<true>;
    advisory: AdvisorySelect<false> | AdvisorySelect<true>;
    'class-news': ClassNewsSelect<false> | ClassNewsSelect<true>;
    'classification-ships': ClassificationShipsSelect<false> | ClassificationShipsSelect<true>;
    classifications: ClassificationsSelect<false> | ClassificationsSelect<true>;
    compliance: ComplianceSelect<false> | ComplianceSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    pdf: PdfSelect<false> | PdfSelect<true>;
    'portal-resources': PortalResourcesSelect<false> | PortalResourcesSelect<true>;
    regulations: RegulationsSelect<false> | RegulationsSelect<true>;
    'regulatory-updates': RegulatoryUpdatesSelect<false> | RegulatoryUpdatesSelect<true>;
    'research-programs': ResearchProgramsSelect<false> | ResearchProgramsSelect<true>;
    'research-report-categories': ResearchReportCategoriesSelect<false> | ResearchReportCategoriesSelect<true>;
    'research-reports': ResearchReportsSelect<false> | ResearchReportsSelect<true>;
    software: SoftwareSelect<false> | SoftwareSelect<true>;
    'training-course-categories': TrainingCourseCategoriesSelect<false> | TrainingCourseCategoriesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: 'zh';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  order?: number | null;
  slug: string;
  name: string;
  /**
   * If selected, Layout and SEO tabs will be ignored.
   */
  redirectTo?: {
    relationTo: 'pages';
    value: number | Page;
  } | null;
  path?: string | null;
  fullTitle?: string | null;
  content?: unknown[] | null;
  seo?: {
    title?: string | null;
    description?: string | null;
  };
  parent?: (number | null) | Page;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advisory-subcategory".
 */
export interface AdvisorySubcategory {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  order?: number | null;
  parent?: (number | null) | Advisory;
  excerpt?: string | null;
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advisory".
 */
export interface Advisory {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  'is-promoted'?: string | null;
  order?: number | null;
  excerpt?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  'service-description'?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class-news".
 */
export interface ClassNew {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  date?: string | null;
  issue?: string | null;
  image?: (number | null) | Media;
  category?:
    | (
        | 'Maritime rules and safety'
        | 'Passenger ship'
        | 'Maritime energy transition'
        | 'Classification and certification'
      )
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  webflowId?: string | null;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    webp360?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    webp480?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    webp768?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    webp1024?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    webp1440?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    webp1920?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classification-ships".
 */
export interface ClassificationShip {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  order?: number | null;
  image?: (number | null) | Media;
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classifications".
 */
export interface Classification {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  order?: number | null;
  image?: (number | null) | Media;
  'link-url'?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compliance".
 */
export interface Compliance {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  category?: ('欧盟 Fit for 55' | 'IMO' | '欧盟拆船法规') | null;
  order?: number | null;
  'name-2'?: string | null;
  excerpt?: string | null;
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  order?: number | null;
  title?: string | null;
  'title-2'?: string | null;
  address?: string | null;
  'postal-code'?: string | null;
  phone?: string | null;
  fax?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  date?: string | null;
  issue?: string | null;
  image?: (number | null) | Media;
  category?:
    | (
        | 'Maritime rules and safety'
        | 'Passenger ship'
        | 'Maritime energy transition'
        | 'Classification and certification'
      )
    | null;
  body?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdf".
 */
export interface Pdf {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-resources".
 */
export interface PortalResource {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  order?: number | null;
  excerpt?: string | null;
  link?: string | null;
  'link-text'?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulations".
 */
export interface Regulation {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  code?: string | null;
  date?: string | null;
  category?: ('LR规则' | '指南说明' | '船舶材料与资格程序') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulatory-updates".
 */
export interface RegulatoryUpdate {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  date?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-programs".
 */
export interface ResearchProgram {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  link?: string | null;
  date?: string | null;
  image?: (number | null) | Media;
  'is-light-bg'?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-report-categories".
 */
export interface ResearchReportCategory {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-reports".
 */
export interface ResearchReport {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  link?: string | null;
  category?: (number | null) | ResearchReportCategory;
  date?: string | null;
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "software".
 */
export interface Software {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  excerpt?: string | null;
  order?: number | null;
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-course-categories".
 */
export interface TrainingCourseCategory {
  id: number;
  /**
   * The original Webflow ID for this item
   */
  webflowId?: string | null;
  name: string;
  slug: string;
  order?: number | null;
  image?: (number | null) | Media;
  link2?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'advisory-subcategory';
        value: number | AdvisorySubcategory;
      } | null)
    | ({
        relationTo: 'advisory';
        value: number | Advisory;
      } | null)
    | ({
        relationTo: 'class-news';
        value: number | ClassNew;
      } | null)
    | ({
        relationTo: 'classification-ships';
        value: number | ClassificationShip;
      } | null)
    | ({
        relationTo: 'classifications';
        value: number | Classification;
      } | null)
    | ({
        relationTo: 'compliance';
        value: number | Compliance;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'pdf';
        value: number | Pdf;
      } | null)
    | ({
        relationTo: 'portal-resources';
        value: number | PortalResource;
      } | null)
    | ({
        relationTo: 'regulations';
        value: number | Regulation;
      } | null)
    | ({
        relationTo: 'regulatory-updates';
        value: number | RegulatoryUpdate;
      } | null)
    | ({
        relationTo: 'research-programs';
        value: number | ResearchProgram;
      } | null)
    | ({
        relationTo: 'research-report-categories';
        value: number | ResearchReportCategory;
      } | null)
    | ({
        relationTo: 'research-reports';
        value: number | ResearchReport;
      } | null)
    | ({
        relationTo: 'software';
        value: number | Software;
      } | null)
    | ({
        relationTo: 'training-course-categories';
        value: number | TrainingCourseCategory;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  webflowId?: T;
  order?: T;
  slug?: T;
  name?: T;
  redirectTo?: T;
  path?: T;
  fullTitle?: T;
  content?: T | {};
  seo?:
    | T
    | {
        title?: T;
        description?: T;
      };
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advisory-subcategory_select".
 */
export interface AdvisorySubcategorySelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  order?: T;
  parent?: T;
  excerpt?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "advisory_select".
 */
export interface AdvisorySelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  'is-promoted'?: T;
  order?: T;
  excerpt?: T;
  body?: T;
  'service-description'?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "class-news_select".
 */
export interface ClassNewsSelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  date?: T;
  issue?: T;
  image?: T;
  category?: T;
  body?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classification-ships_select".
 */
export interface ClassificationShipsSelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  order?: T;
  image?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "classifications_select".
 */
export interface ClassificationsSelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  order?: T;
  image?: T;
  'link-url'?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "compliance_select".
 */
export interface ComplianceSelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  category?: T;
  order?: T;
  'name-2'?: T;
  excerpt?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  order?: T;
  title?: T;
  'title-2'?: T;
  address?: T;
  'postal-code'?: T;
  phone?: T;
  fax?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  date?: T;
  issue?: T;
  image?: T;
  category?: T;
  body?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pdf_select".
 */
export interface PdfSelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portal-resources_select".
 */
export interface PortalResourcesSelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  order?: T;
  excerpt?: T;
  link?: T;
  'link-text'?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulations_select".
 */
export interface RegulationsSelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  code?: T;
  date?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "regulatory-updates_select".
 */
export interface RegulatoryUpdatesSelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  date?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-programs_select".
 */
export interface ResearchProgramsSelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  link?: T;
  date?: T;
  image?: T;
  'is-light-bg'?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-report-categories_select".
 */
export interface ResearchReportCategoriesSelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "research-reports_select".
 */
export interface ResearchReportsSelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  link?: T;
  category?: T;
  date?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "software_select".
 */
export interface SoftwareSelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  excerpt?: T;
  order?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "training-course-categories_select".
 */
export interface TrainingCourseCategoriesSelect<T extends boolean = true> {
  webflowId?: T;
  name?: T;
  slug?: T;
  order?: T;
  image?: T;
  link2?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  webflowId?: T;
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        webp360?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        webp480?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        webp768?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        webp1024?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        webp1440?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        webp1920?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}